#!/bin/sh
cran2deb depend ls aliases >populate_depend_aliases
cran2deb depend ls force >populate_forcedep
cran2deb depend ls sysreq >populate_sysreq
echo NOTE: you need to update populate_licenses manually!
